import { redirect } from 'next/navigation';
import { getSupabasePublicEnv } from './supabase-env';

/**
 * Allowlist of trusted redirect origins for the OAuth consent flow.
 * Only URLs starting with these origins are permitted as redirect targets,
 * preventing open-redirect / XSS via javascript: URIs.
 */
export const ALLOWED_REDIRECT_ORIGINS = [
    'https://api.notion.com',
    'https://www.notion.so',
    'https://www.perplexity.ai',
    'https://mcp.mietevo.de',
    'https://mietevo.de',
    'http://localhost:8787',
    'http://localhost:3000',
    'http://localhost:3333',
    'http://127.0.0.1:8787',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3333',
    'http://127.0.0.1:54321',
    // Allow any Cloudflare Pages preview deploy for development
    ...(process.env.NEXT_PUBLIC_EXTRA_REDIRECT_ORIGINS
        ? process.env.NEXT_PUBLIC_EXTRA_REDIRECT_ORIGINS.split(',')
        : []),
];

function isAllowedProtocol(parsed: URL): boolean {
    if (parsed.protocol === 'https:') return true;
    if (parsed.protocol === 'http:') {
        return parsed.hostname === 'localhost' || parsed.hostname === '127.0.0.1' || parsed.hostname === '[::1]';
    }
    return false;
}

/**
 * Validates a redirect URL against the allowlist.
 * Only HTTPS URLs (or local loopback HTTP URLs) whose origin is in the allowlist are accepted.
 */
export function isValidRedirect(url: string | undefined | null): boolean {
    if (!url) return false;
    try {
        const parsed = new URL(url);
        if (!isAllowedProtocol(parsed)) return false;
        return ALLOWED_REDIRECT_ORIGINS.some(allowed => parsed.origin === allowed);
    } catch {
        return false;
    }
}

/**
 * Validates a Supabase-internal redirect URL (e.g. redirect_to on auto_approved flows).
 * These are callback URLs generated by the Supabase Auth server itself — they point to
 * the project's Supabase instance and are safe to follow unconditionally.
 */
export function isValidSupabaseRedirect(url: string | undefined | null): boolean {
    if (!url) return false;
    const { url: supabaseUrl } = getSupabasePublicEnv();
    const activeUrl = supabaseUrl || process.env.NEXT_PUBLIC_SUPABASE_URL;
    if (!activeUrl) return false; // fail-closed
    try {
        const parsed = new URL(url);
        if (!isAllowedProtocol(parsed)) return false;
        const supabaseOrigin = new URL(activeUrl).origin;
        return parsed.origin === supabaseOrigin;
    } catch {
        return false;
    }
}

/**
 * Server-side safe redirect for OAuth flows.
 * Falls back to an error page if the redirect URL is untrusted.
 */
export function safeServerRedirect(url: string | undefined | null): never {
    if (isValidRedirect(url)) {
        redirect(url!);
    }

    if (isValidSupabaseRedirect(url)) {
        console.info('[OAuth] Allowing Supabase-internal redirect:', url);
        redirect(url!);
    }

    console.error('[OAuth] Blocked server-side redirect to untrusted origin:', url);
    redirect(`/oauth/consent?error=true&message=${encodeURIComponent('Ungültige Weiterleitungs-URL. Zugriff verweigert aus Sicherheitsgründen.')}`);
}
